package dev.voir.reflector.sample.ledger

import androidx.room3.ColumnInfo
import androidx.room3.ColumnTypeConverters
import androidx.room3.Entity
import androidx.room3.Index
import androidx.room3.PrimaryKey
import dev.voir.reflector.sync.persistence.SyncColumnConverters
import kotlin.uuid.Uuid

/**
 * Movement of money on a wallet.
 *
 * The reference to the wallet is a plain column and not a foreign key on purpose: a transaction may
 * arrive from the server before the wallet it belongs to, because collections are synchronised
 * independently and nothing orders them.
 *
 * @property id Identifier generated by the client.
 * @property walletId Wallet the movement belongs to.
 * @property amountMinor Amount in minor currency units; integers keep money exact.
 * @property comment Note the user left, or `null` when there is none.
 */
@Entity(
    tableName = "ledger_transaction",
    indices = [Index(value = ["wallet_id"])],
)
@ColumnTypeConverters(SyncColumnConverters::class)
data class LedgerTransaction(
    @PrimaryKey @ColumnInfo(name = "id") val id: Uuid,
    @ColumnInfo(name = "wallet_id") val walletId: Uuid,
    @ColumnInfo(name = "amount_minor") val amountMinor: Long,
    @ColumnInfo(name = "comment") val comment: String?,
)
