package dev.voir.reflector.sample.ledger

import androidx.room3.ColumnInfo
import androidx.room3.ColumnTypeConverters
import androidx.room3.Entity
import androidx.room3.PrimaryKey
import dev.voir.reflector.sync.persistence.SyncColumnConverters
import kotlin.uuid.Uuid

/**
 * Account money is held on, as the demonstration application models it.
 *
 * The library knows nothing about this class: it stores only the fact that a wallet with this
 * identifier is dirty or clean, and asks the adapter for its state when a push needs one.
 *
 * @property id Identifier generated by the client, shared with the server as is.
 * @property title Name the user gave the wallet.
 * @property currency ISO-4217 code of the wallet's currency.
 */
@Entity(tableName = "wallet")
@ColumnTypeConverters(SyncColumnConverters::class)
data class Wallet(
    @PrimaryKey @ColumnInfo(name = "id") val id: Uuid,
    @ColumnInfo(name = "title") val title: String,
    @ColumnInfo(name = "currency") val currency: String,
)
