package dev.voir.reflector.sync.protocol

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline
import kotlin.uuid.Uuid

/**
 * Identifier of one blob, unique inside its collection.
 *
 * Generated by the application, like an entity identifier and for the same reason: a photograph
 * taken offline has to have an identity before anything reaches a server, because the document that
 * references it is written in the same local transaction. A server-assigned key would mean that
 * document could not be written until the device was online.
 *
 * A blob is immutable, so the identifier names one sequence of bytes for as long as it exists.
 * Replacing a file means a new identifier and a document that points at it, never new bytes under
 * this one — which is what makes a blob unable to conflict, and every operation on it idempotent.
 *
 * UUIDv7 is the recommendation, exactly as for entities, and nothing in the protocol reads the
 * version nibble.
 *
 * @property value UUID value preserved across system boundaries; any version is accepted.
 */
@Serializable
@JvmInline
public value class BlobId(
    public val value: Uuid,
)
