package dev.voir.reflector.sync.protocol

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline
import kotlin.uuid.Uuid

/**
 * Identifier of a single entity, unique inside its collection and entity type.
 *
 * Identifiers are generated by the application so that a record created offline keeps its identity
 * once it reaches the server: the protocol has no notion of a server-assigned key. UUIDv7 is the
 * recommendation rather than a requirement — a time-ordered key keeps the server's indexes local —
 * and nothing in the protocol reads the version nibble or depends on the ordering.
 *
 * @property value UUID value preserved across system boundaries; any version is accepted.
 */
@Serializable
@JvmInline
public value class EntityId(
    public val value: Uuid,
)
