package dev.voir.reflector.sync.protocol

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline
import kotlin.uuid.Uuid

/**
 * Identifier of a push group, which doubles as the idempotency key of the push.
 *
 * A group is applied atomically by the server, which stores the produced result under this
 * identifier. Re-sending a group after a lost response returns the stored result instead of
 * applying it twice, so the client may retry a push it never saw the outcome of.
 *
 * @property value UUID value generated by the client. The queue is ordered by insertion rather
 *   than by this identifier, so its version buys nothing here and none is required.
 */
@Serializable
@JvmInline
public value class GroupId(
    public val value: Uuid,
)
