package dev.voir.reflector.sync.server.postgres

import dev.voir.reflector.sync.protocol.SyncProtocolJson
import kotlinx.serialization.json.JsonObject
import org.jetbrains.exposed.v1.core.ReferenceOption
import org.jetbrains.exposed.v1.core.dao.id.UuidTable
import org.jetbrains.exposed.v1.datetime.timestamp
import org.jetbrains.exposed.v1.json.jsonb

/**
 * Current state of every entity the module stores.
 *
 * The module stores documents but models nothing about them: for it [data] is opaque `jsonb`. It
 * holds them because a patch can only be merged by whoever has the document — moving that to the
 * host would make every push a read-modify-write through host code, and the correctness of
 * versioning would then depend on somebody else's implementation for every entity type.
 */
internal object EntitiesTable : UuidTable("sync.entities") {
    /** Collection the entity belongs to. */
    val collection = reference("collection_id", CollectionsTable, onDelete = ReferenceOption.CASCADE)

    /** Type of the entity. */
    val entityType = varchar("entity_type", CollectionsTable.COLLECTION_LENGTH)

    /** Identifier of the entity, generated by the client. */
    val entityId = uuid("entity_id")

    /** Sequence of the batch that last changed the entity; this is the version clients compare. */
    val version = long("version")

    /** Stored document, or `null` once the entity has been deleted. */
    val data = jsonb<JsonObject>("data", SyncProtocolJson.format).nullable()

    /**
     * Whether the entity is a tombstone.
     *
     * Deleted rows are kept for the retention window: a client whose cursor is still inside it has
     * to learn about the deletion from the log, and one that arrives later learns it from the
     * entity's absence in a snapshot.
     */
    val isDeleted = bool("is_deleted")

    /** Sequence of the last batch touching the entity; retention sweeps tombstones by it. */
    val lastSeq = long("last_seq")

    /** When the entity was first written. */
    val createdAt = timestamp("created_at")

    /** When the entity was last written. */
    val updatedAt = timestamp("updated_at")

    init {
        uniqueIndex("uq_entities__collection_id__entity_type__entity_id", collection, entityType, entityId)
    }
}
